spring:
  application:
    name: 331-backend
  profiles:
    active:
      db
  datasource:
    url: jdbc:mysql://localhost:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A
      expiration: 3600000
      refresh-token:
        expiration: 604800000
  gcs:
    bucket: imageuploadcompo.firebasestorage.app

